apiVersion: v1
name: magda-dap-connector
description: A Helm chart for Magda DAP Connector
version: "0.0.57-0"
home: "https://github.com/magda-io/magda-dap-connector"
sources: ["https://github.com/magda-io/magda-dap-connector"]
